language: ruby
rvm:
        - 2.1.2
        - rbx
notifications:
        email: false
script: CODECLIMATE_REPO_TOKEN=1486a4589ae9326a7a567e9599edd0ecd306c65e5f359cc724855c2a34efe67b xvfb-run rspec
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - JRUBY_OPTS=-Xcext.enabled=true
before_install: 
        - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update
        - sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qtlocation5-dev qtsensors5-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt4-default
        - sudo locale-gen --no-archive es_CO.UTF-8
        - cd spec/dummy
        - psql -c 'CREATE DATABASE sivel2sjr_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - cp db/datos-basicas.sql db/datos-basicas.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - sed -e "s/SET lock_timeout = 0;//g" db/datos-basicas.sql.conlock >db/datos-basicas.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sivel2:indices
        - cd ../..

